"""add user timezone

Revision ID: 0357a97984d6
Revises: 9803a2be51e1
Create Date: 2026-08-28 19:56:36.572611

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0357a97984d6'
down_revision: str | None = '9803a2be51e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
