"""task done + completed_at

Revision ID: 3cbd063419ee
Revises: 49907c03111e
Create Date: 2026-08-28 16:38:05.738939

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3cbd063419ee'
down_revision: str | None = '49907c03111e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('done', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_done'), ['done'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_done'))
        batch_op.drop_column('completed_at')
        batch_op.drop_column('done')

    # ### end Alembic commands ###
