"""add event_overrides

Revision ID: 9803a2be51e1
Revises: 3cbd063419ee
Create Date: 2026-08-28 19:11:42.776561

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '9803a2be51e1'
down_revision: str | None = '3cbd063419ee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_start', sa.DateTime(), nullable=False),
    sa.Column('canceled', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_overrides_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_overrides_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_overrides')),
    sa.UniqueConstraint('event_id', 'occurrence_start', name='uq_override_instance')
    )
    with op.batch_alter_table('event_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_overrides_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_overrides_occurrence_start'), ['occurrence_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_overrides_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_overrides_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_overrides_occurrence_start'))
        batch_op.drop_index(batch_op.f('ix_event_overrides_event_id'))

    op.drop_table('event_overrides')
    # ### end Alembic commands ###
